// Copyright © OpenTTS contributors
// License: MIT
//
// End-to-end parity tests against the Python ailuntx mlx-audio reference.
//
// Goldens live next to this file under MiMoTests/Fixtures/golden/ (mel, codes,
// final text). Generated by tools/dump_mimo_golden.py.

import Foundation
import MLX
import MLXLMCommon
import MLXLMTokenizers
import Testing

@testable import MLXAudio

/// Directory containing the mimo LLM weights. Override via env var, otherwise
/// default to LM Studio's standard cache location.
private let mimoLLMDir = URL(fileURLWithPath:
    ProcessInfo.processInfo.environment["MIMO_MODEL_DIR"]
    ?? NSString(string: "~/.lmstudio/models/mlx-community/MiMo-V2.5-ASR-MLX")
        .expandingTildeInPath
)

private let fixturesDir = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .appendingPathComponent("MiMoTests/Fixtures")

private struct GoldenText: Codable {
    let text: String
}

@Suite("MimoParity")
struct MimoParityTests {

    // MARK: - Stage 1: mel-spectrogram parity

    @Test @MainActor
    func melMatchesPythonGolden() throws {
        try requireFixtures()
        for clip in clipNames {
            let audioURL = fixturesDir.appendingPathComponent("audio/\(clip).wav")
            let goldenURL = fixturesDir.appendingPathComponent("golden/\(clip).mel.npy")

            let waveform = try MiMoAudio.loadAudio(audioURL)
            let mel = MiMoAudio.logMelSpectrogram(waveform)

            let golden = try loadNpyAsArray(goldenURL)
            // Spec §6.2: cosine similarity ≥ 0.9999. Absolute differences
            // up to ~1e-2 are expected from Float32 STFT/mel-filter rounding
            // and don't affect downstream code/RVQ/transcript correctness
            // (validated end-to-end below).
            try assertCosineMatch(
                actual: mel,
                expected: golden,
                minCosine: 0.9999,
                label: "\(clip) mel"
            )
        }
    }

    // MARK: - Stage 2: RVQ codes parity (compile-only here; runtime requires loaded model)

    @Test @MainActor
    func rvqCodesPipelineCompiles() throws {
        // This test is a compile-time gate: it instantiates the audio
        // tokenizer with default config and calls .encode on a zero mel,
        // proving the type plumbing (Conv1d, RoPE tables, 32 layers, RVQ
        // stack) actually constructs and runs end-to-end.
        //
        // Skipped on Intel Macs; weight-bearing parity is gated behind
        // endToEndTranscript below.
        try requireFixtures()

        let tok = MiMoAudioTokenizer(config: MiMoTokenizerConfig())
        let mel = MLXArray.zeros([128, 100]).asType(.float32)
        let codes = tok.encode(mel, nQ: 8)
        #expect(codes.shape[0] == 8, "RVQ should emit 8 channels (nQ=8 requested)")
        #expect(codes.dtype == .int32)
    }

    // MARK: - Stage 3: end-to-end transcript parity (requires LM Studio weights)

    @Test @MainActor
    func endToEndTranscriptMatchesPython() async throws {
        try requireFixtures()
        guard FileManager.default.fileExists(atPath: mimoLLMDir.path) else {
            Issue.record("Skipping: mimo weights not at \(mimoLLMDir.path)")
            return
        }

        let engine = STT.mimo(localDirectory: mimoLLMDir)
        try await engine.load()

        for clip in clipNames {
            let audioURL = fixturesDir.appendingPathComponent("audio/\(clip).wav")
            let goldenURL = fixturesDir.appendingPathComponent("golden/\(clip).text.json")

            let expectedJson = try Data(contentsOf: goldenURL)
            let expected = try JSONDecoder().decode(GoldenText.self, from: expectedJson).text

            let lang: MiMoPrompt.Language = clip == "en_short" ? .english : .auto
            let result = try await engine.transcribe(audioURL, language: lang)

            let cer = characterErrorRate(actual: result.text, expected: expected)
            #expect(
                cer <= 0.05,
                """
                Transcript divergence beyond tolerance for \(clip):
                  expected: \(expected)
                  actual:   \(result.text)
                  CER:      \(cer)
                """
            )
        }
    }

    // MARK: - Helpers

    private var clipNames: [String] { ["zh_short", "en_short", "code_switch"] }

    private func requireFixtures() throws {
        let audioDir = fixturesDir.appendingPathComponent("audio")
        guard FileManager.default.fileExists(atPath: audioDir.path) else {
            Issue.record("Skipping: fixtures missing at \(fixturesDir.path)")
            throw FixtureMissingError()
        }
    }

    /// Minimal float32 .npy reader. Only handles 2-D contiguous arrays with
    /// 'descr': '<f4' (native little-endian float32), which is exactly what
    /// the dumper produces.
    private func loadNpyAsArray(_ url: URL) throws -> MLXArray {
        let raw = try Data(contentsOf: url)

        // .npy format: 0x93 N U M P Y (6 bytes), major (1), minor (1),
        // headerLen (uint16 LE for v1.x), header (ASCII dict), data.
        guard raw.count > 10 else {
            throw NPYError.invalid("file too short")
        }
        guard raw[0] == 0x93,
              raw[1...5].map({ Character(UnicodeScalar($0)) }) == Array("NUMPY") else {
            throw NPYError.invalid("magic mismatch")
        }
        let major = raw[6]
        guard major == 1 else {
            throw NPYError.invalid("only npy v1.x supported, got v\(major)")
        }
        let headerLen = Int(raw[8]) | (Int(raw[9]) << 8)
        let headerEnd = 10 + headerLen
        guard let header = String(data: raw[10..<headerEnd], encoding: .utf8) else {
            throw NPYError.invalid("header decode")
        }

        // Parse {'descr': '<f4', 'fortran_order': False, 'shape': (a, b)}
        guard header.contains("'<f4'") else {
            throw NPYError.invalid("unsupported dtype (need '<f4'): \(header)")
        }
        // Specifically check the fortran_order field, not random "True"
        // appearances elsewhere in the header.
        if header.contains("'fortran_order': True") {
            throw NPYError.invalid("fortran_order: True not supported")
        }
        let shape = parseNPYShape(header)

        let body = raw[headerEnd...]
        let count = body.count / MemoryLayout<Float>.size
        let floats = body.withUnsafeBytes { ptr -> [Float] in
            let bound = ptr.bindMemory(to: Float.self)
            return Array(UnsafeBufferPointer(start: bound.baseAddress, count: count))
        }

        return MLXArray(floats).reshaped(shape)
    }

    private func parseNPYShape(_ header: String) -> [Int] {
        guard let open = header.firstIndex(of: "("),
              let close = header.firstIndex(of: ")") else { return [] }
        let inner = header[header.index(after: open) ..< close]
        return inner
            .split(separator: ",")
            .compactMap { s -> Int? in
                let trimmed = s.trimmingCharacters(in: .whitespaces)
                return trimmed.isEmpty ? nil : Int(trimmed)
            }
    }

    private func assertCosineMatch(
        actual: MLXArray,
        expected: MLXArray,
        minCosine: Float,
        label: String
    ) throws {
        guard actual.shape == expected.shape else {
            Issue.record("[\(label)] shape mismatch: actual=\(actual.shape) expected=\(expected.shape)")
            return
        }
        let a = actual.asType(.float32).reshaped([-1])
        let b = expected.asType(.float32).reshaped([-1])
        let dot = (a * b).sum().item(Float.self)
        let normA = MLX.sqrt((a * a).sum()).item(Float.self)
        let normB = MLX.sqrt((b * b).sum()).item(Float.self)
        let cos = dot / (normA * normB + 1e-12)
        #expect(
            cos >= minCosine,
            "[\(label)] cosine similarity = \(cos) < \(minCosine)"
        )
    }

    private func characterErrorRate(actual: String, expected: String) -> Double {
        // Lowercase + strip whitespace and common punctuation for comparison.
        let strip: (String) -> String = {
            $0.lowercased()
                .components(separatedBy: CharacterSet.punctuationCharacters)
                .joined()
                .components(separatedBy: .whitespacesAndNewlines)
                .joined()
        }
        let a = Array(strip(actual))
        let b = Array(strip(expected))
        let n = a.count, m = b.count
        if n == 0 && m == 0 { return 0 }
        if n == 0 || m == 0 { return 1 }

        var prev = Array(0 ... m)
        var curr = Array(repeating: 0, count: m + 1)
        for i in 1 ... n {
            curr[0] = i
            for j in 1 ... m {
                let cost = a[i - 1] == b[j - 1] ? 0 : 1
                curr[j] = min(curr[j - 1] + 1, prev[j] + 1, prev[j - 1] + cost)
            }
            swap(&prev, &curr)
        }
        return Double(prev[m]) / Double(max(n, m))
    }
}

private struct FixtureMissingError: Error {}

private enum NPYError: Error {
    case invalid(String)
}
